version: '3.9'

services:
  database:
    image: postgres:15
    container_name: ${ORG_SLUG}-org-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aluminate-network

  mongo:
    image: mongo:6.0
    container_name: ${ORG_SLUG}-org-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_root
      MONGO_INITDB_ROOT_PASSWORD: 24b29e5b1f2558774a1057f23dd8e37cf5c41e0cbe6196faebfdcedb5a0d9849
    volumes:
      - mongo_data:/data/db
    networks:
      - aluminate-network

  redis:
    image: redis:7
    container_name: ${ORG_SLUG}-org-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - aluminate-network

  backend:
    image: aluminate/org-backend:latest
    container_name: ${ORG_SLUG}-org-backend
    depends_on:
      - database
      - redis
      - mongo
    environment:
      ORGANIZATION_PORT: 8098
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/aluminatedb
      SPRING_DATA_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_DATA_REDIS_URI: ${SPRING_DATA_REDIS_URI}
      SPRING_DATA_MONGO_URI: mongodb://mongo_root:24b29e5b1f2558774a1057f23dd8e37cf5c41e0cbe6196faebfdcedb5a0d9849@mongo:27017/aluminate_chat?authSource=admin
      GLOBAL_BACKEND_URL: "http://global-backend:8080"
      ORG_SLUG: ${ORG_SLUG}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      API_PREFIX: "${API_PREFIX}"
      API_PREFIX_GLOBAL: ${API_PREFIX_GLOBAL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_ORGANIZATION_PRIVATE_KEY: ${SPRING_ORGANIZATION_PRIVATE_KEY}
      SPRING_GLOBAL_PUBLIC_KEY: ${SPRING_GLOBAL_PUBLIC_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PAYHERE_MERCHANT_ID: ${PAYHERE_MERCHANT_ID}
      PAYHERE_SECRET: ${PAYHERE_SECRET}
      NEXT_PUBLIC_GLOBAL_PUBLIC_KEY: ${SPRING_GLOBAL_PUBLIC_KEY}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ORG_SLUG}-backend.rule=Host(`${ORG_SLUG}.api.${TRAEFIK_HOST}`)"
      - "traefik.http.routers.${ORG_SLUG}-backend.entrypoints=websecure"
      - "traefik.http.routers.${ORG_SLUG}-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.${ORG_SLUG}-backend.loadbalancer.server.port=8098"
    networks:
      - aluminate-network

  frontend:
    image: aluminate/org-frontend:${ORG_SLUG}
    container_name: ${ORG_SLUG}-org-frontend
    depends_on:
      - backend
    environment:
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ORG_SLUG}-frontend.rule=Host(`${ORG_SLUG}.${TRAEFIK_HOST}`)"
      - "traefik.http.routers.${ORG_SLUG}-frontend.entrypoints=websecure"
      - "traefik.http.routers.${ORG_SLUG}-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.${ORG_SLUG}-frontend.loadbalancer.server.port=3000"
    networks:
      - aluminate-network

volumes:
  pgdata:
  mongo_data:
  redis_data:

networks:
  aluminate-network:
    external: true
    name: aluminate-global-network