services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aluminate-network

  backend:
    build:
      context: ./aluminate-organization-backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8098:8098"
    networks:
      - aluminate-network

  frontend:
    build:
      context: ./aluminate-organization-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - aluminate-network

volumes:
  pgdata:

networks:
  aluminate-network: