spring.application.name=aluminate-organization-backend
server.port=8098
spring.datasource.url=jdbc:postgresql://database:5432/aluminatedb
spring.datasource.username=senira
spring.datasource.password=2002




