# Application Configuration
spring.application.name=aluminate-organization-backend
server.port=8098

# for local testing on your own local postgres uncomment this
spring.docker.compose.enabled=false

# Database Configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

# uncomment this for local testing on localhost
# Local testing configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/aluminatedb

spring.datasource.username=satheera
spring.datasource.password=satheera
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging to see table creation
logging.level.org.hibernate.SQL=DEBUG

#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration

#gemini api key
gemini.api.key=AIzaSyC--aV3v26YzkaDymS4bLIsPHXUzBWt_vQ
api.prefix=/api/v1/portal

# JWT Configuration
JWT_SECRET=d9f3a7e2c6b84f9a8d42e1c7f35b0d6e
JWT_EXPIRES_IN=86400000

#smtp server configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pulasthiabishake06@gmail.com
spring.mail.password=kwma reeu rpow dear
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PayHere Configuration
payhere.merchant.id=1224501
payhere.merchant.secret=YOUR_MERCHANT_SECRET_KEY
payhere.currency=LKR
payhere.sandbox=true

# PayHere URLs (Update these with your actual domain)
payhere.return.url=http://localhost:3000/donations/success
payhere.cancel.url=http://localhost:3000/donations/cancel
payhere.notify.url=http://your-domain.com/api/v1/donation/payment/notify



