#FROM maven:3.8.5-openjdk-17-slim
#WORKDIR /app
#COPY . .
#EXPOSE 8098
#CMD ["mvn", "spring-boot:run"]

# this docker file is only suitable for dev, for production we need a separate one. this one probably enables hot reloading.
FROM eclipse-temurin:21-jdk
WORKDIR /app

# Install Maven
RUN apt-get update && \
    apt-get install -y maven && \
    apt-get clean

# The pom.xml and src will be mounted as volumes
EXPOSE 8098

# Run with spring-boot:run for development (enables hot reload)
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]
